#!/usr/bin/env bash
# Run this script as root on each remote host before using it as a runner target.
# Usage: sudo bash setup-agent.sh <ssh-user>
# Example: sudo bash setup-agent.sh c

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Error: this script must be run as root (sudo bash setup-agent.sh <ssh-user>)" >&2
  exit 1
fi

if [[ $# -lt 1 ]]; then
  echo "Usage: sudo bash setup-agent.sh <ssh-user>" >&2
  exit 1
fi

SSH_USER="$1"
RUNNER_USER="github-runner"
INSTALL_BASE="/opt/actions-runner"
SUDOERS_FILE="/etc/sudoers.d/actions-runner"

# Verify the SSH user exists
if ! id "$SSH_USER" &>/dev/null; then
  echo "Error: user '$SSH_USER' does not exist on this host" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# 1. Create the dedicated service user that the runner daemon will run as
# ---------------------------------------------------------------------------
if id "$RUNNER_USER" &>/dev/null; then
  echo "[setup] Service user '$RUNNER_USER' already exists, skipping."
else
  useradd \
    --system \
    --no-create-home \
    --shell /usr/sbin/nologin \
    --comment "GitHub Actions runner service account" \
    "$RUNNER_USER"
  echo "[setup] Created service user: $RUNNER_USER"
fi

# ---------------------------------------------------------------------------
# 2. Create the base install directory, owned by the SSH user
#    Subdirectories (one per repo) are created by index.js without sudo.
# ---------------------------------------------------------------------------
mkdir -p "$INSTALL_BASE"
chown "${SSH_USER}:${SSH_USER}" "$INSTALL_BASE"
chmod 755 "$INSTALL_BASE"
echo "[setup] Created $INSTALL_BASE (owner: $SSH_USER)"

# ---------------------------------------------------------------------------
# 3. Write a minimal sudoers file — only what index.js actually needs
# ---------------------------------------------------------------------------
SVCSH_PATH="$INSTALL_BASE/*/svc.sh"

cat > "$SUDOERS_FILE" <<EOF
# GitHub Actions runner — generated by setup-agent.sh
# SSH user : $SSH_USER
# Service  : $RUNNER_USER
# Base dir : $INSTALL_BASE

$SSH_USER ALL=(ALL) NOPASSWD: $SVCSH_PATH
EOF

chmod 440 "$SUDOERS_FILE"

# Validate the file before we leave it in place
if visudo -cf "$SUDOERS_FILE"; then
  echo "[setup] Sudoers file written and validated: $SUDOERS_FILE"
else
  rm -f "$SUDOERS_FILE"
  echo "Error: sudoers file failed validation and was removed" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "Host is ready. Make sure config.json has:"
echo "  \"serviceUser\": \"$RUNNER_USER\""
echo ""
echo "Granted sudo (NOPASSWD) for $SSH_USER:"
echo "  $SVCSH_PATH"
